Repository haru-mandal-art/haru-mandalart, pull requests merged in 2024-03, with the labels that each got.

#39 [Feature] todo week 로직
  core/data/src/main/java/com/coldblue/data/mapper/CurrentGroupMapper.kt
  core/data/src/main/java/com/coldblue/data/repo/CurrentGroupRepository.kt
  core/data/src/main/java/com/coldblue/data/repo/CurrentGroupRepositoryImpl.kt
  core/database/src/main/java/com/coldblue/database/dao/CurrentGroupDao.kt
  core/database/src/main/java/com/coldblue/database/entity/CurrentGroupEntity.kt
  core/domain/src/main/java/com/coldblue/domain/todogroup/GetCurrentGroupUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/todogroup/GetGroupWithCurrentUseCase.kt
  core/model/src/main/java/com/coldblue/model/CurrentGroup.kt
  feature/todo/src/main/java/com/coldblue/todo/BottomSheetUiState.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoBottomSheet.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoGroupBottomSheet.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoScreen.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoUiState.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoViewModel.kt
Labels: Feature

#40 [Feature] Manda - Data, Model, UI 수정
  core/data/src/main/java/com/coldblue/data/mapper/Mapper.kt
  core/database/src/main/java/com/coldblue/database/entity/MandaDetailEntity.kt
  core/database/src/main/java/com/coldblue/database/entity/MandaKeyEntity.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMMandaEmptyButton.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMMandaFillButton.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMMandaMainButton.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMMandaOutlineButton.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/theme/Color.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/theme/Type.kt
  core/model/src/main/java/com/coldblue/model/Manda.kt
  feature/manda/src/main/java/com/coldblue/mandalart/MandaViewModel.kt
  feature/manda/src/main/java/com/coldblue/mandalart/model/MandaUI.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/content/InitializedMandaContent.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/content/UnInitializedMandaContent.kt
  feature/manda/src/main/java/com/coldblue/mandalart/state/MandaUIState.kt
  feature/manda/src/main/java/com/coldblue/mandalart/util/MandaUtils.kt
Labels: Feature

#43 [Feature] TodoBottomSheet
  core/model/src/main/java/com/coldblue/model/Todo.kt
  core/model/src/main/java/com/coldblue/model/ToggleInfo.kt
  feature/todo/src/main/java/com/coldblue/todo/BottomSheetUiState.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoBottomSheet.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoScreen.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoViewModel.kt
Labels: Feature

#44 [Feature] Manda - Manda Component Zoom Out
  core/data/src/main/java/com/coldblue/data/repo/MandaDetailRepositoryImpl.kt
  core/data/src/main/java/com/coldblue/data/repo/MandaKeyRepositoryImpl.kt
  core/database/src/main/java/com/coldblue/database/entity/MandaDetailEntity.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMMandaEmptyButton.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/theme/Type.kt
  feature/manda/src/main/java/com/coldblue/mandalart/MandaViewModel.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/content/InitializedMandaContent.kt
Labels: Feature

#48 [Feature] todo bottomsheet 완성
  core/data/src/main/java/com/coldblue/data/mapper/CurrentGroupMapper.kt
  core/database/src/main/java/com/coldblue/database/dao/TodoDao.kt
  core/model/src/main/java/com/coldblue/model/CurrentGroup.kt
  core/model/src/main/java/com/coldblue/model/Todo.kt
  core/model/src/main/java/com/coldblue/model/ToggleInfo.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoBottomSheet.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoScreen.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoUiState.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoViewModel.kt
Labels: Feature

#50 [Feature] Manda Bottom Sheet
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMMandaMainButton.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMTextField.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/theme/Color.kt
  feature/manda/src/main/java/com/coldblue/mandalart/MandaViewModel.kt
  feature/manda/src/main/java/com/coldblue/mandalart/model/MandaColorInfo.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/MandaScreen.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/content/InitializedMandaContent.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/content/MandaBottomSheet.kt
  feature/manda/src/main/java/com/coldblue/mandalart/state/BottomSheetUIState.kt
  feature/manda/src/main/java/com/coldblue/mandalart/state/MandaBottomSheetUIState.kt
Labels: Feature

#51 [Feature] notification Alarm 기본
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/coldblue/haru_mandalart/HMApplication.kt
  app/src/main/java/com/coldblue/haru_mandalart/NotificationModule.kt
  app/src/main/java/com/coldblue/haru_mandalart/navigation/HMNavHost.kt
  app/src/main/java/com/coldblue/haru_mandalart/notification/Counter.kt
  app/src/main/java/com/coldblue/haru_mandalart/notification/TodoNotificationReceiver.kt
  app/src/main/java/com/coldblue/haru_mandalart/notification/TodoNotificationServiceImpl.kt
  app/src/main/java/com/coldblue/haru_mandalart/ui/HMState.kt
  core/data/src/main/AndroidManifest.xml
  core/data/src/main/java/com/coldblue/data/alarm/AlarmReceiver.kt
  core/data/src/main/java/com/coldblue/data/alarm/AlarmScheduler.kt
  core/data/src/main/java/com/coldblue/data/alarm/AlarmSchedulerImpl.kt
  core/data/src/main/java/com/coldblue/data/alarm/BootCompletedReceiver.kt
  core/data/src/main/java/com/coldblue/data/di/AlarmModule.kt
  core/data/src/main/java/com/coldblue/data/navi/Route.kt
  core/data/src/main/java/com/coldblue/data/notification/TodoNotificationService.kt
  core/data/src/main/java/com/coldblue/data/repo/TodoRepositoryImpl.kt
  core/data/src/main/java/com/coldblue/data/util/DateTimeUtil.kt
  core/data/src/main/res/drawable/ic_android_black_24dp.xml
  core/model/src/main/java/com/coldblue/model/AlarmItem.kt
  feature/history/src/main/java/com/coldblue/history/navigation/HistoryNavigation.kt
  feature/login/src/main/java/com/coldblue/login/navigation/LoginNavigation.kt
  feature/manda/src/main/java/com/coldblue/mandalart/navigation/MandaNavigation.kt
  feature/setting/src/main/java/com/coldblue/setting/SettingScreen.kt
  feature/setting/src/main/java/com/coldblue/setting/SettingViewModel.kt
  feature/setting/src/main/java/com/coldblue/setting/navigation/SettingNavigation.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoBottomSheet.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoScreen.kt
  feature/todo/src/main/java/com/coldblue/todo/navigation/TodoNavigation.kt
  feature/tutorial/src/main/java/com/coldblue/tutorial/navigation/TutorialNavigation.kt
Labels: Feature

#52 [Feature] Manda - Bottom Sheet 구현 완료
  core/data/src/main/java/com/coldblue/data/repo/MandaDetailRepository.kt
  core/data/src/main/java/com/coldblue/data/repo/MandaDetailRepositoryImpl.kt
  core/data/src/main/java/com/coldblue/data/repo/MandaKeyRepository.kt
  core/data/src/main/java/com/coldblue/data/repo/MandaKeyRepositoryImpl.kt
  core/database/src/main/java/com/coldblue/database/dao/MandaDetailDao.kt
  core/database/src/main/java/com/coldblue/database/dao/MandaKeyDao.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMMandaFillButton.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMMandaOutlineButton.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMTextField.kt
  core/domain/src/main/java/com/coldblue/domain/manda/DeleteMandaAllUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/manda/DeleteMandaDetailUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/manda/DeleteMandaKeyUseCase.kt
  feature/manda/src/main/java/com/coldblue/mandalart/MandaViewModel.kt
  feature/manda/src/main/java/com/coldblue/mandalart/model/MandaUI.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/MandaBottomSheet.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/MandaScreen.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/content/InitializedMandaContent.kt
  feature/manda/src/main/java/com/coldblue/mandalart/state/MandaBottomSheetUIState.kt
  feature/manda/src/main/java/com/coldblue/mandalart/state/MandaUIState.kt
  feature/manda/src/main/java/com/coldblue/mandalart/util/MandaUtils.kt
Labels: Feature

#53 [Feature] setting ui
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMTopBar.kt
  feature/history/src/main/java/com/coldblue/history/HistoryScreen.kt
  feature/setting/src/main/java/com/coldblue/setting/SettingScreen.kt
  feature/setting/src/main/java/com/coldblue/setting/SettingViewModel.kt
  feature/setting/src/main/java/com/coldblue/setting/content/SettingContent.kt
Labels: Feature

#54 [Feature] time logic 수정
  app/src/main/java/com/coldblue/haru_mandalart/notification/TodoNotificationReceiver.kt
  app/src/main/java/com/coldblue/haru_mandalart/notification/TodoNotificationServiceImpl.kt
  core/data/src/main/java/com/coldblue/data/alarm/AlarmReceiver.kt
  core/data/src/main/java/com/coldblue/data/alarm/BootCompletedReceiver.kt
  core/data/src/main/java/com/coldblue/data/notification/TodoNotificationService.kt
  core/data/src/main/java/com/coldblue/data/util/DateTimeUtil.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoBottomSheet.kt
Labels: Feature

#55 [Feature] History - Controller
  core/data/src/main/java/com/coldblue/data/repo/TodoRepository.kt
  core/data/src/main/java/com/coldblue/data/repo/TodoRepositoryImpl.kt
  core/data/src/main/java/com/coldblue/data/util/DateTimeUtil.kt
  core/database/src/main/java/com/coldblue/database/dao/TodoDao.kt
  core/database/src/main/java/com/coldblue/database/entity/MandaDetailEntity.kt
  core/domain/src/main/java/com/coldblue/domain/todo/GetTodoYearRangeUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/todo/GetYearlyExistTodoDateUseCase.kt
  core/model/src/main/java/com/coldblue/model/Manda.kt
  feature/history/src/main/java/com/coldblue/history/HistoryScreen.kt
  feature/history/src/main/java/com/coldblue/history/HistoryUiState.kt
  feature/history/src/main/java/com/coldblue/history/HistoryViewModel.kt
  feature/history/src/main/java/com/coldblue/history/content/HistoryContent.kt
  feature/history/src/main/java/com/coldblue/history/util/HistoryUtil.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoViewModel.kt
Labels: Feature

#60 [Feature] setting items
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/coldblue/haru_mandalart/MainActivity.kt
  app/src/main/java/com/coldblue/haru_mandalart/di/NotificationModule.kt
  app/src/main/java/com/coldblue/haru_mandalart/di/SettingModule.kt
  app/src/main/java/com/coldblue/haru_mandalart/util/SettingHelperImpl.kt
  app/src/main/res/anim/anim_slide_left_enter.xml
  app/src/main/res/anim/anim_slide_left_exit.xml
  app/src/main/res/anim/anim_slide_right_enter.xml
  app/src/main/res/anim/anim_slide_right_exit.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/oss.xml
  build.gradle.kts
  core/data/src/main/java/com/coldblue/data/util/SettingHelper.kt
  feature/history/src/main/java/com/coldblue/history/HistoryScreen.kt
  feature/setting/src/main/java/com/coldblue/setting/SettingScreen.kt
  feature/setting/src/main/java/com/coldblue/setting/SettingViewModel.kt
  feature/setting/src/main/java/com/coldblue/setting/content/SettingContent.kt
  gradle/libs.versions.toml
Labels: Feature

#62 [Feature] Histroy - Day, Year Controller 구현 완료
  core/data/src/main/java/com/coldblue/data/repo/TodoRepositoryImpl.kt
  core/database/src/main/java/com/coldblue/database/convert/LocalDateConvert.kt
  core/database/src/main/java/com/coldblue/database/dao/TodoDao.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/theme/Color.kt
  feature/history/src/main/java/com/coldblue/history/HistoryScreen.kt
  feature/history/src/main/java/com/coldblue/history/HistoryUiState.kt
  feature/history/src/main/java/com/coldblue/history/HistoryViewModel.kt
  feature/history/src/main/java/com/coldblue/history/content/HistoryContent.kt
  feature/history/src/main/java/com/coldblue/history/util/HistoryUtil.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoViewModel.kt
Labels: Feature

#63 [Feature] Sync를 위한 OriginId 컬럼 추가
  core/data/src/main/java/com/coldblue/data/mapper/Mapper.kt
  core/database/src/main/java/com/coldblue/database/entity/MandaDetailEntity.kt
  core/database/src/main/java/com/coldblue/database/entity/MandaKeyEntity.kt
Labels: Feature

#68 [Feature] todo 빈칸, time null 처리
  core/data/src/main/java/com/coldblue/data/alarm/AlarmSchedulerImpl.kt
  core/data/src/main/java/com/coldblue/data/repo/TodoRepositoryImpl.kt
  core/model/src/main/java/com/coldblue/model/AlarmItem.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoBottomSheet.kt
Labels: Feature

#70 [Feature] sync read repository
  app/src/main/java/com/coldblue/haru_mandalart/HMApplication.kt
  app/src/main/java/com/coldblue/haru_mandalart/MainActivity.kt
  core/data/src/main/java/com/coldblue/data/di/RepositoryModule.kt
  core/data/src/main/java/com/coldblue/data/mapper/TodoMapper.kt
  core/data/src/main/java/com/coldblue/data/repository/UserRepositoryImpl.kt
  core/data/src/main/java/com/coldblue/data/repository/manda/MandaDetailRepository.kt
  core/data/src/main/java/com/coldblue/data/repository/manda/MandaDetailRepositoryImpl.kt
  core/data/src/main/java/com/coldblue/data/repository/manda/MandaKeyRepository.kt
  core/data/src/main/java/com/coldblue/data/repository/manda/MandaKeyRepositoryImpl.kt
  core/data/src/main/java/com/coldblue/data/repository/todo/CurrentGroupRepository.kt
  core/data/src/main/java/com/coldblue/data/repository/todo/CurrentGroupRepositoryImpl.kt
  core/data/src/main/java/com/coldblue/data/repository/todo/TodoGroupRepository.kt
  core/data/src/main/java/com/coldblue/data/repository/todo/TodoGroupRepositoryImpl.kt
  core/data/src/main/java/com/coldblue/data/repository/todo/TodoRepository.kt
  core/data/src/main/java/com/coldblue/data/repository/todo/TodoRepositoryImpl.kt
  core/data/src/main/java/com/coldblue/data/sync/SyncReadHelper.kt
  core/data/src/main/java/com/coldblue/data/sync/SyncWriteHelper.kt
  core/data/src/main/java/com/coldblue/data/sync/SyncWriteHelperImpl.kt
  core/data/src/main/java/com/coldblue/data/sync/worker/SyncReadWorker.kt
  core/data/src/main/java/com/coldblue/data/sync/worker/SyncWriteWorker.kt
  core/data/src/main/java/com/coldblue/data/util/DateTimeUtil.kt
  core/database/src/main/java/com/coldblue/database/dao/TodoDao.kt
  core/database/src/main/java/com/coldblue/database/entity/TodoEntity.kt
  core/datastore/src/main/java/com/coldblue/datastore/UserDataSource.kt
  core/datastore/src/main/java/com/coldblue/datastore/UserDataSourceImpl.kt
  core/domain/src/main/java/com/coldblue/domain/manda/DeleteMandaAllUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/manda/DeleteMandaDetailUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/manda/DeleteMandaKeyUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/manda/GetDetailMandaUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/manda/GetKeyMandaUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/manda/UpsertMandaDetailUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/manda/UpsertMandaKeyUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/todo/DeleteTodoUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/todo/GetTodoUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/todo/GetTodoYearRangeUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/todo/GetYearlyExistTodoDateUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/todo/ToggleTodoUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/todo/UpsertTodoUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/todogroup/DeleteCurrentGroupUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/todogroup/DeleteTodoGroupUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/todogroup/GetCurrentGroupUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/todogroup/GetGroupWithCurrentUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/todogroup/GetTodoGroupUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/todogroup/UpsertCurrentGroupUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/todogroup/UpsertTodoGroupUseCase.kt
  core/model/src/main/java/com/coldblue/model/Todo.kt
  core/network/src/main/java/com/coldblue/network/datasourceImpl/TodoDataSourceImpl.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoBottomSheet.kt
Labels: Feature

#72 [Feature] Manda - Zoom 버튼 위치, 모양 수정
  core/designsystem/src/main/java/com/coldblue/designsystem/__IconPack.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/iconpack/ZoomIn.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/iconpack/ZoomOut.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/content/InitializedMandaContent.kt
Labels: Feature

#73 [Feature] 로그아웃, 탈퇴
  app/src/main/java/com/coldblue/haru_mandalart/MainActivity.kt
  core/data/src/main/java/com/coldblue/data/alarm/AlarmScheduler.kt
  core/data/src/main/java/com/coldblue/data/alarm/AlarmSchedulerImpl.kt
  core/data/src/main/java/com/coldblue/data/di/SyncModule.kt
  core/data/src/main/java/com/coldblue/data/repository/UserRepository.kt
  core/data/src/main/java/com/coldblue/data/repository/UserRepositoryImpl.kt
  core/data/src/main/java/com/coldblue/data/repository/manda/MandaKeyRepository.kt
  core/data/src/main/java/com/coldblue/data/repository/manda/MandaKeyRepositoryImpl.kt
  core/data/src/main/java/com/coldblue/data/sync/SyncHelper.kt
  core/data/src/main/java/com/coldblue/data/sync/SyncHelperImpl.kt
  core/data/src/main/java/com/coldblue/data/sync/worker/SyncReadWorker.kt
  core/data/src/main/java/com/coldblue/data/util/LoginHelper.kt
  core/data/src/main/java/com/coldblue/data/util/LoginHelperImpl.kt
  core/database/src/main/java/com/coldblue/database/AppDataBase.kt
  core/database/src/main/java/com/coldblue/database/dao/AppDao.kt
  core/database/src/main/java/com/coldblue/database/dao/MandaKeyDao.kt
  core/database/src/main/java/com/coldblue/database/di/DaoModule.kt
  core/datastore/src/main/java/com/coldblue/datastore/UpdateTimeDataSource.kt
  core/datastore/src/main/java/com/coldblue/datastore/UpdateTimeDataSourceImpl.kt
  core/datastore/src/main/java/com/coldblue/datastore/UserDataSource.kt
  core/datastore/src/main/java/com/coldblue/datastore/UserDataSourceImpl.kt
  core/domain/src/main/java/com/coldblue/domain/user/GetEmailUseCase.kt
  core/network/src/main/java/com/coldblue/network/SupabaseDataSource.kt
  core/network/src/main/java/com/coldblue/network/SupabaseDataSourceImpl.kt
  feature/login/src/main/java/com/coldblue/login/LoginScreen.kt
  feature/login/src/main/java/com/coldblue/login/LoginViewModel.kt
  feature/setting/src/main/java/com/coldblue/setting/SettingScreen.kt
  feature/setting/src/main/java/com/coldblue/setting/SettingViewModel.kt
  feature/setting/src/main/java/com/coldblue/setting/content/SettingContent.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoViewModel.kt
Labels: Feature

#74 [Feature] Manda - Status, Mandalart 기능 개선 및 오류 해결
  core/data/src/main/java/com/coldblue/data/repository/manda/MandaDetailRepositoryImpl.kt
  core/database/src/main/java/com/coldblue/database/dao/MandaDetailDao.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMMandaCompleteButton.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMMandaEmptyButton.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMMandaFillButton.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMMandaOutlineButton.kt
  core/model/src/main/java/com/coldblue/model/Manda.kt
  feature/manda/src/main/java/com/coldblue/mandalart/model/MandaUI.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/MandaBottomSheet.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/content/InitializedMandaContent.kt
  feature/manda/src/main/java/com/coldblue/mandalart/state/MandaBottomSheetUIState.kt
  feature/manda/src/main/java/com/coldblue/mandalart/state/MandaUIState.kt
  feature/manda/src/main/java/com/coldblue/mandalart/util/MandaUtils.kt
Labels: Bug, Feature

#75 [Feature] Manda - Mandalart, bottom Sheet 수정 작업
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMTextField.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/theme/Color.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/MandaBottomSheet.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/content/InitializedMandaContent.kt
  feature/manda/src/main/java/com/coldblue/mandalart/util/MandaUtils.kt
Labels: Feature

#76 [Feature] Manda - 디테일 개선
  feature/manda/src/main/java/com/coldblue/mandalart/screen/MandaBottomSheet.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/content/InitializedMandaContent.kt
Labels: Feature

#77 [Feature] todo group, current group 체크
  core/data/src/main/java/com/coldblue/data/repository/todo/CurrentGroupRepositoryImpl.kt
  core/data/src/main/java/com/coldblue/data/repository/todo/TodoGroupRepository.kt
  core/data/src/main/java/com/coldblue/data/repository/todo/TodoGroupRepositoryImpl.kt
  core/data/src/main/java/com/coldblue/data/sync/SyncHelperImpl.kt
  core/data/src/main/java/com/coldblue/data/sync/worker/SyncReadWorker.kt
  core/data/src/main/java/com/coldblue/data/sync/worker/SyncWriteWorker.kt
  core/database/src/main/java/com/coldblue/database/dao/CurrentGroupDao.kt
  core/database/src/main/java/com/coldblue/database/dao/TodoGroupDao.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/DeleteDialog.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMTextField.kt
  core/domain/src/main/java/com/coldblue/domain/todogroup/UpsertTodoGroupUseCase.kt
  feature/setting/src/main/java/com/coldblue/setting/content/SettingContent.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoBottomSheet.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoGroupBottomSheet.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoScreen.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoViewModel.kt
  feature/todo/src/main/java/com/coldblue/todo/dialog/SimpleDialog.kt
Labels: Feature

#78 [Feature] HMTextField maxLen 추가
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMTextField.kt
  core/model/src/main/java/com/coldblue/model/ToggleInfo.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/MandaBottomSheet.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/content/UnInitializedMandaContent.kt
  feature/manda/src/main/java/com/coldblue/mandalart/state/MandaBottomSheetUIState.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoGroupBottomSheet.kt
Labels: Feature

#79 [Feature] History 기능 개선
  feature/history/src/main/java/com/coldblue/history/HistoryScreen.kt
  feature/history/src/main/java/com/coldblue/history/HistoryUiState.kt
  feature/history/src/main/java/com/coldblue/history/content/HistoryContent.kt
  feature/history/src/main/java/com/coldblue/history/util/HistoryUtil.kt
Labels: Feature

#80 [Feature] Manda - Status, Mandalart, Bottom Sheet 디테일 수정
  core/designsystem/src/main/java/com/coldblue/designsystem/__IconPack.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMTextField.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/iconpack/Newzoomin.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/iconpack/Newzoomout.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/iconpack/ZoomIn.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/iconpack/ZoomOut.kt
  feature/manda/src/main/java/com/coldblue/mandalart/MandaViewModel.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/MandaBottomSheet.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/content/InitializedMandaContent.kt
  feature/manda/src/main/java/com/coldblue/mandalart/util/MandaUtils.kt
Labels: Feature

#81 [Feature] current group 로직 수정
  core/data/src/main/java/com/coldblue/data/repository/todo/CurrentGroupRepository.kt
  core/data/src/main/java/com/coldblue/data/repository/todo/CurrentGroupRepositoryImpl.kt
  core/database/src/main/java/com/coldblue/database/dao/CurrentGroupDao.kt
  core/domain/src/main/java/com/coldblue/domain/todogroup/GetCurrentGroupUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/todogroup/GetGroupWithCurrentUseCase.kt
Labels: Feature

#82 [Feature] History - top title, date title 로직 수정
  core/data/src/main/java/com/coldblue/data/util/DateTimeUtil.kt
  feature/history/src/main/java/com/coldblue/history/content/HistoryContent.kt
Labels: Feature

#85 [Feature] History 디자인, 데이터 로직, 사용성 개선
  core/data/src/main/java/com/coldblue/data/repository/todo/TodoRepository.kt
  core/data/src/main/java/com/coldblue/data/repository/todo/TodoRepositoryImpl.kt
  core/data/src/main/java/com/coldblue/data/util/DateTimeUtil.kt
  core/database/src/main/java/com/coldblue/database/dao/TodoDao.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/theme/Type.kt
  core/domain/src/main/java/com/coldblue/domain/todo/GetUniqueTodoCountByDateUseCase.kt
  feature/history/src/main/java/com/coldblue/history/HistoryUiState.kt
  feature/history/src/main/java/com/coldblue/history/HistoryViewModel.kt
  feature/history/src/main/java/com/coldblue/history/content/HistoryContent.kt
  feature/history/src/main/java/com/coldblue/history/util/HistoryUtil.kt
Labels: Feature

#83 [Feature] timepicker 완성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/coldblue/haru_mandalart/notification/Counter.kt
  app/src/main/java/com/coldblue/haru_mandalart/notification/TodoNotificationReceiver.kt
  app/src/main/java/com/coldblue/haru_mandalart/notification/TodoNotificationServiceImpl.kt
  core/data/src/main/java/com/coldblue/data/alarm/AlarmReceiver.kt
  core/data/src/main/java/com/coldblue/data/util/DateTimeUtil.kt
  core/domain/src/main/java/com/coldblue/domain/todo/GetTodoUseCase.kt
  core/model/src/main/java/com/coldblue/model/MyTime.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoBottomSheet.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoGroupBottomSheet.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoScreen.kt
  feature/todo/src/main/java/com/coldblue/todo/dialog/SimpleDialog.kt
Labels: Feature

#88 [Design] notification icon
  app/src/main/java/com/coldblue/haru_mandalart/notification/TodoNotificationServiceImpl.kt
Labels: Design

#92 [Feature] 알림 권한, Setting 알람 On / Off 로직 변경
  app/src/main/java/com/coldblue/haru_mandalart/MainActivity.kt
  core/data/src/main/java/com/coldblue/data/util/PermissionHelper.kt
  core/data/src/main/java/com/coldblue/data/util/PermissionHelperImpl.kt
  core/datastore/src/main/java/com/coldblue/datastore/UserDataSource.kt
  core/datastore/src/main/java/com/coldblue/datastore/UserDataSourceImpl.kt
  feature/setting/build.gradle.kts
  feature/setting/src/main/java/com/coldblue/setting/SettingScreen.kt
  feature/setting/src/main/java/com/coldblue/setting/SettingViewModel.kt
  feature/setting/src/main/java/com/coldblue/setting/content/SettingContent.kt
Labels: Feature

#93 [Featrue] History - 로직 및 오류 개선
  app/src/main/java/com/coldblue/haru_mandalart/MainActivity.kt
  core/data/src/main/java/com/coldblue/data/repository/todo/TodoRepositoryImpl.kt
  core/data/src/main/java/com/coldblue/data/util/DateTimeUtil.kt
  feature/history/src/main/java/com/coldblue/history/HistoryUiState.kt
  feature/history/src/main/java/com/coldblue/history/HistoryViewModel.kt
  feature/history/src/main/java/com/coldblue/history/content/HistoryContent.kt
  feature/history/src/main/java/com/coldblue/history/navigation/HistoryNavigation.kt
  feature/manda/src/main/java/com/coldblue/mandalart/MandaViewModel.kt
  feature/manda/src/main/java/com/coldblue/mandalart/navigation/MandaNavigation.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/MandaBottomSheet.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/content/InitializedMandaContent.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/content/UnInitializedMandaContent.kt
  feature/manda/src/main/java/com/coldblue/mandalart/state/MandaUIState.kt
  feature/manda/src/main/java/com/coldblue/mandalart/util/MandaUtils.kt
  feature/manda/src/main/res/values/Array.xml
  feature/todo/src/main/java/com/coldblue/todo/navigation/TodoNavigation.kt
Labels: Feature

#95 [Feature] update dao 업데이트 타임 추가
  core/data/src/main/AndroidManifest.xml
  core/data/src/main/java/com/coldblue/data/di/RepositoryModule.kt
  core/data/src/main/java/com/coldblue/data/mapper/CurrentGroupMapper.kt
  core/data/src/main/java/com/coldblue/data/mapper/TodoGroupMapper.kt
  core/data/src/main/java/com/coldblue/data/repository/todo/CurrentGroupRepository.kt
  core/data/src/main/java/com/coldblue/data/repository/todo/CurrentGroupRepositoryImpl.kt
  core/data/src/main/java/com/coldblue/data/repository/todo/TodoGroupRepositoryImpl.kt
  core/data/src/main/java/com/coldblue/data/util/ConnectivityManagerNetworkHelper.kt
  core/data/src/main/java/com/coldblue/data/util/LoginHelperImpl.kt
  core/data/src/main/java/com/coldblue/data/util/NetworkHelper.kt
  core/database/src/main/java/com/coldblue/database/dao/CurrentGroupDao.kt
  core/database/src/main/java/com/coldblue/database/dao/TodoGroupDao.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/DeleteDialog.kt
  core/domain/src/main/java/com/coldblue/domain/todogroup/DeleteCurrentGroupUseCase.kt
  core/model/src/main/java/com/coldblue/model/ToggleInfo.kt
  feature/history/src/main/java/com/coldblue/history/HistoryScreen.kt
  feature/history/src/main/java/com/coldblue/history/content/HistoryContent.kt
  feature/history/src/main/java/com/coldblue/history/navigation/HistoryNavigation.kt
  feature/login/src/main/java/com/coldblue/login/LoginScreen.kt
  feature/login/src/main/java/com/coldblue/login/LoginViewModel.kt
  feature/login/src/main/res/drawable/app_icon.xml
  feature/manda/src/main/java/com/coldblue/mandalart/screen/MandaBottomSheet.kt
  feature/setting/src/main/java/com/coldblue/setting/SettingScreen.kt
  feature/setting/src/main/java/com/coldblue/setting/SettingViewModel.kt
  feature/setting/src/main/java/com/coldblue/setting/content/SettingContent.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoBottomSheet.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoEditScreen.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoEditViewModel.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoGroupBottomSheet.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoScreen.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoViewModel.kt
  feature/todo/src/main/java/com/coldblue/todo/component/GroupPicker.kt
  feature/todo/src/main/java/com/coldblue/todo/component/HMTimePicker.kt
  feature/todo/src/main/java/com/coldblue/todo/dialog/SimpleDialog.kt
  feature/todo/src/main/java/com/coldblue/todo/navigation/TodoNavigation.kt
  feature/todo/src/main/java/com/coldblue/todo/uistate/TodoEditUiState.kt
Labels: Feature

#96 [Feature] 외래키 에러 방지
  app/src/main/java/com/coldblue/haru_mandalart/MainActivity.kt
  core/data/src/main/java/com/coldblue/data/mapper/CurrentGroupWithNameMapper.kt
  core/database/src/main/java/com/coldblue/database/entity/CurrentGroupEntity.kt
  feature/setting/src/main/java/com/coldblue/setting/SettingScreen.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoViewModel.kt
Labels: Feature

#100 [Bug] History - Year Picker 중복 오류 해결
  core/data/src/main/java/com/coldblue/data/util/DateTimeUtil.kt
Labels: Feature

#99 [Feature] 배포 전 수정사항 반영
  app/src/main/java/com/coldblue/haru_mandalart/MainActivity.kt
  core/data/src/main/java/com/coldblue/data/di/PermissionModule.kt
  core/data/src/main/java/com/coldblue/data/repository/manda/MandaKeyRepository.kt
  core/data/src/main/java/com/coldblue/data/repository/manda/MandaKeyRepositoryImpl.kt
  core/data/src/main/java/com/coldblue/data/repository/user/UserRepository.kt
  core/data/src/main/java/com/coldblue/data/repository/user/UserRepositoryImpl.kt
  core/data/src/main/java/com/coldblue/data/util/LoginHelper.kt
  core/data/src/main/java/com/coldblue/data/util/LoginHelperImpl.kt
  core/data/src/main/java/com/coldblue/data/util/PermissionHelper.kt
  core/data/src/main/java/com/coldblue/data/util/PermissionHelperImpl.kt
  core/database/src/main/java/com/coldblue/database/dao/MandaKeyDao.kt
  core/datastore/src/main/java/com/coldblue/datastore/UserDataSource.kt
  core/datastore/src/main/java/com/coldblue/datastore/UserDataSourceImpl.kt
  core/domain/src/main/java/com/coldblue/domain/manda/DeleteMandaKeyUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/user/UpdateMandaInitStateUseCase.kt
  feature/history/src/main/java/com/coldblue/history/content/HistoryContent.kt
  feature/manda/src/main/java/com/coldblue/mandalart/MandaViewModel.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/MandaBottomSheet.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/content/UnInitializedMandaContent.kt
  feature/setting/src/main/java/com/coldblue/setting/SettingViewModel.kt
  feature/setting/src/main/java/com/coldblue/setting/content/SettingContent.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoGroupBottomSheet.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoScreen.kt
  feature/todo/src/main/java/com/coldblue/todo/dialog/SimpleDialog.kt
Labels: Feature

#98 [Sync] Manda Sync 로직 개선, 오류 해결
  core/data/src/main/java/com/coldblue/data/mapper/MandaDetailMapper.kt
  core/data/src/main/java/com/coldblue/data/mapper/MandaKeyMapper.kt
  core/data/src/main/java/com/coldblue/data/repository/manda/MandaDetailRepositoryImpl.kt
  core/data/src/main/java/com/coldblue/data/repository/manda/MandaKeyRepositoryImpl.kt
  core/database/src/main/java/com/coldblue/database/dao/MandaDetailDao.kt
  core/database/src/main/java/com/coldblue/database/dao/MandaKeyDao.kt
  core/domain/src/main/java/com/coldblue/domain/manda/DeleteMandaKeyUseCase.kt
  core/model/src/main/java/com/coldblue/model/Manda.kt
  core/model/src/main/java/com/coldblue/model/NetworkModel.kt
  core/network/src/main/java/com/coldblue/network/datasourceImpl/MandaKeyDataSourceImpl.kt
  core/network/src/main/java/com/coldblue/network/model/NetworkMandaDetail.kt
  core/network/src/main/java/com/coldblue/network/model/NetworkMandaKey.kt
  feature/manda/src/main/java/com/coldblue/mandalart/MandaViewModel.kt
  feature/manda/src/main/java/com/coldblue/mandalart/model/MandaUI.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/MandaBottomSheet.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/MandaScreen.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/content/InitializedMandaContent.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/content/UnInitializedMandaContent.kt
  feature/manda/src/main/java/com/coldblue/mandalart/state/MandaUIState.kt
  feature/manda/src/main/java/com/coldblue/mandalart/util/MandaUtils.kt
Labels: Feature

#102 [Feature] current group 변경사항
  core/data/src/main/java/com/coldblue/data/repository/manda/MandaKeyRepositoryImpl.kt
  core/data/src/main/java/com/coldblue/data/repository/todo/CurrentGroupRepositoryImpl.kt
  core/database/src/main/java/com/coldblue/database/dao/CurrentGroupDao.kt
Labels: Feature

#103 [Feature] current 그룹 외래키 해결
  core/data/src/main/java/com/coldblue/data/mapper/CurrentGroupMapper.kt
  core/data/src/main/java/com/coldblue/data/mapper/TodoMapper.kt
  core/data/src/main/java/com/coldblue/data/repository/todo/CurrentGroupRepositoryImpl.kt
  core/data/src/main/java/com/coldblue/data/repository/todo/TodoGroupRepositoryImpl.kt
  core/data/src/main/java/com/coldblue/data/sync/worker/SyncReadWorker.kt
  core/data/src/main/java/com/coldblue/data/sync/worker/SyncWriteWorker.kt
  core/database/src/main/java/com/coldblue/database/dao/CurrentGroupDao.kt
  core/database/src/main/java/com/coldblue/database/dao/TodoGroupDao.kt
  core/database/src/main/java/com/coldblue/database/entity/TodoEntity.kt
Labels: Feature

#104 [Feature] time format 이슈 해결
  core/data/src/main/java/com/coldblue/data/alarm/BootCompletedReceiver.kt
  core/data/src/main/java/com/coldblue/data/mapper/TodoMapper.kt
  core/data/src/main/java/com/coldblue/data/repository/todo/TodoGroupRepositoryImpl.kt
  core/data/src/main/java/com/coldblue/data/repository/todo/TodoRepositoryImpl.kt
  core/data/src/main/java/com/coldblue/data/util/DateTimeUtil.kt
  core/data/src/main/java/com/coldblue/data/util/LoginHelperImpl.kt
  core/database/src/main/java/com/coldblue/database/convert/LocalDateTimeConverter.kt
  core/database/src/main/java/com/coldblue/database/dao/AppDao.kt
  core/database/src/main/java/com/coldblue/database/dao/MandaKeyDao.kt
  core/database/src/main/java/com/coldblue/database/dao/TodoDao.kt
  core/database/src/main/java/com/coldblue/database/dao/TodoGroupDao.kt
  core/database/src/main/java/com/coldblue/database/entity/TodoEntity.kt
  core/model/src/main/java/com/coldblue/model/Todo.kt
  core/network/src/main/java/com/coldblue/network/model/NetworkTodo.kt
  feature/login/src/main/java/com/coldblue/login/LoginViewModel.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoEditScreen.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoEditViewModel.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoScreen.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoViewModel.kt
Labels: Feature

#105 [Feature] todo group 바텀시트 선택한 투두그룹 제외 표출
  core/data/src/main/java/com/coldblue/data/mapper/TodoMapper.kt
  core/data/src/main/java/com/coldblue/data/repository/todo/TodoGroupRepository.kt
  core/data/src/main/java/com/coldblue/data/repository/todo/TodoGroupRepositoryImpl.kt
  core/data/src/main/java/com/coldblue/data/repository/todo/TodoRepositoryImpl.kt
  core/database/src/main/java/com/coldblue/database/dao/CurrentGroupDao.kt
  core/database/src/main/java/com/coldblue/database/dao/TodoDao.kt
  core/database/src/main/java/com/coldblue/database/dao/TodoGroupDao.kt
  core/domain/src/main/java/com/coldblue/domain/todogroup/UpsertTodoGroupUseCase.kt
  core/model/src/main/java/com/coldblue/model/ToggleInfo.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoEditScreen.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoScreen.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoViewModel.kt
  feature/todo/src/main/java/com/coldblue/todo/component/GroupPicker.kt
  feature/todo/src/main/java/com/coldblue/todo/dialog/SimpleDialog.kt
Labels: Feature

#106 [Feature] Manda, Todo 디자인, 기능 변경사항 반영
  app/src/main/java/com/coldblue/haru_mandalart/ui/HMState.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMMandaMainButton.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/MandaBottomSheet.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/content/InitializedMandaContent.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/content/UnInitializedMandaContent.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoBottomSheet.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoEditScreen.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoGroupBottomSheet.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoScreen.kt
Labels: Feature

#107 [Feature] todo sync 수정
  core/data/src/main/java/com/coldblue/data/mapper/TodoMapper.kt
  core/database/src/main/java/com/coldblue/database/dao/CurrentGroupDao.kt
  core/database/src/main/java/com/coldblue/database/dao/TodoDao.kt
  core/database/src/main/java/com/coldblue/database/dao/TodoGroupDao.kt
Labels: Feature

#108 [Feature] todo sync 수정
  app/src/main/java/com/coldblue/haru_mandalart/MainActivity.kt
  core/database/src/main/java/com/coldblue/database/dao/CurrentGroupDao.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoEditScreen.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoEditViewModel.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoViewModel.kt
  feature/todo/src/main/java/com/coldblue/todo/component/GroupPicker.kt
  feature/todo/src/main/java/com/coldblue/todo/uistate/TodoEditUiState.kt
Labels: Feature

#109 [Feature] History Screen To EditTodo Screen 오류 수정 1
  app/src/main/java/com/coldblue/haru_mandalart/navigation/HMNavHost.kt
  app/src/main/java/com/coldblue/haru_mandalart/ui/HMApp.kt
  app/src/main/java/com/coldblue/haru_mandalart/ui/HMState.kt
  core/data/src/main/java/com/coldblue/data/util/DateTimeUtil.kt
  feature/history/src/main/java/com/coldblue/history/HistoryScreen.kt
  feature/history/src/main/java/com/coldblue/history/HistoryViewModel.kt
  feature/history/src/main/java/com/coldblue/history/content/HistoryContent.kt
  feature/history/src/main/java/com/coldblue/history/navigation/HistoryNavigation.kt
  feature/manda/src/main/java/com/coldblue/mandalart/navigation/MandaNavigation.kt
  feature/todo/src/main/java/com/coldblue/todo/navigation/TodoNavigation.kt
Labels: Bug

#110 [Feature] todo edit screen 전환시 히스토리 클릭 상태
  feature/history/src/main/java/com/coldblue/history/HistoryViewModel.kt
  feature/history/src/main/java/com/coldblue/history/content/HistoryContent.kt
Labels: Feature

#111 [Feature] HistoryScreen To EditScreen 오류 해결
  feature/history/src/main/java/com/coldblue/history/content/HistoryContent.kt
Labels: Feature

#114 [Bug] 기기 재프팅 시 Alarm 로직 수정
  core/data/src/main/java/com/coldblue/data/alarm/AlarmReceiver.kt
  core/data/src/main/java/com/coldblue/data/alarm/AlarmSchedulerImpl.kt
Labels: Bug

#113 [Feature] NetworkTodo 오타 수정
  core/data/src/main/java/com/coldblue/data/mapper/TodoMapper.kt
  core/network/src/main/java/com/coldblue/network/model/NetworkTodo.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoEditScreen.kt
Labels: Feature

#115 [Feature] 비회원 사용자
  app/src/main/java/com/coldblue/haru_mandalart/MainActivity.kt
  core/data/src/main/java/com/coldblue/data/di/SyncModule.kt
  core/data/src/main/java/com/coldblue/data/sync/SyncHelperImpl.kt
  core/data/src/main/java/com/coldblue/data/util/LoginHelper.kt
  core/data/src/main/java/com/coldblue/data/util/LoginHelperImpl.kt
  core/data/src/main/java/com/coldblue/data/util/LoginState.kt
  core/datastore/src/main/java/com/coldblue/datastore/UserDataSource.kt
  core/datastore/src/main/java/com/coldblue/datastore/UserDataSourceImpl.kt
  feature/login/src/main/java/com/coldblue/login/LoginScreen.kt
  feature/login/src/main/java/com/coldblue/login/LoginViewModel.kt
  feature/setting/build.gradle.kts
  feature/setting/src/main/java/com/coldblue/setting/SettingScreen.kt
  feature/setting/src/main/java/com/coldblue/setting/SettingViewModel.kt
  feature/setting/src/main/java/com/coldblue/setting/content/SettingContent.kt
  feature/setting/src/main/java/com/coldblue/setting/exception/LoginException.kt
  feature/setting/src/main/java/com/coldblue/setting/state/LoginUiState.kt
Labels: Feature

#116 [Feature] Login Button UI 수정
  feature/login/src/main/java/com/coldblue/login/LoginScreen.kt
Labels: Feature

#117 [Feature] 로그아웃후 비회원 로그인시 계정표시 수정
  core/data/src/main/java/com/coldblue/data/sync/SyncHelper.kt
  core/data/src/main/java/com/coldblue/data/sync/SyncHelperImpl.kt
  core/data/src/main/java/com/coldblue/data/util/LoginHelperImpl.kt
  core/datastore/src/main/java/com/coldblue/datastore/UserDataSourceImpl.kt
  feature/history/src/main/java/com/coldblue/history/content/HistoryContent.kt
Labels: Feature
