Repository haru-mandal-art/haru-mandalart, pull requests merged in 2024-04, with the labels that each got.

#118 [Feature] Splash Screen API 도입
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/coldblue/haru_mandalart/MainActivity.kt
  app/src/main/res/values/themes.xml
  core/data/src/main/java/com/coldblue/data/repository/todo/CurrentGroupRepositoryImpl.kt
  core/data/src/main/java/com/coldblue/data/util/LoginHelperImpl.kt
  core/database/src/main/java/com/coldblue/database/dao/CurrentGroupDao.kt
  core/datastore/src/main/java/com/coldblue/datastore/UserDataSourceImpl.kt
  feature/login/src/main/java/com/coldblue/login/LoginScreen.kt
  gradle/libs.versions.toml
Labels: Feature

#120 [Refactoring] Change to String Resource
  app/src/main/java/com/coldblue/haru_mandalart/MainActivity.kt
  app/src/main/java/com/coldblue/haru_mandalart/notification/TodoNotificationServiceImpl.kt
  app/src/main/java/com/coldblue/haru_mandalart/util/SettingHelperImpl.kt
  app/src/main/res/values/strings.xml
  feature/history/src/main/java/com/coldblue/history/HistoryScreen.kt
  feature/history/src/main/java/com/coldblue/history/content/HistoryContent.kt
  feature/history/src/main/res/values/strings.xml
  feature/login/src/main/java/com/coldblue/login/LoginScreen.kt
  feature/login/src/main/res/values/strings.xml
  feature/manda/src/main/java/com/coldblue/mandalart/screen/MandaBottomSheet.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/content/InitializedMandaContent.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/content/UnInitializedMandaContent.kt
  feature/manda/src/main/res/values/arrays.xml
  feature/manda/src/main/res/values/strings.xml
  feature/setting/src/main/java/com/coldblue/setting/content/SettingContent.kt
  feature/setting/src/main/java/com/coldblue/setting/exception/LoginException.kt
  feature/setting/src/main/java/com/coldblue/setting/state/LoginUiState.kt
  feature/setting/src/main/res/values/strings.xml
Labels: Refactoring

#124 [Setting] Build Type 구분
  app/build.gradle.kts
  app/proguard-rules.pro
  core/network/build.gradle.kts
  core/network/src/main/java/com/coldblue/network/di/SupabaseModule.kt
  feature/history/src/main/java/com/coldblue/history/HistoryViewModel.kt
Labels: Setting

#126 [Feature] 투두, 기록 기능 제거
  app/src/main/java/com/coldblue/haru_mandalart/navigation/HMNavHost.kt
  app/src/main/java/com/coldblue/haru_mandalart/navigation/TopLevelDestination.kt
  app/src/main/java/com/coldblue/haru_mandalart/ui/HMApp.kt
  app/src/main/java/com/coldblue/haru_mandalart/ui/HMState.kt
  feature/manda/src/main/java/com/coldblue/mandalart/navigation/MandaNavigation.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/MandaScreen.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/content/InitializedMandaContent.kt
Labels: Feature

#127 [Refactoring] Changing String Resource
  app/src/main/java/com/coldblue/haru_mandalart/MainActivity.kt
  feature/login/src/main/java/com/coldblue/login/LoginScreen.kt
  feature/login/src/main/res/values/strings.xml
  feature/setting/src/main/java/com/coldblue/setting/content/SettingContent.kt
Labels: Refactoring

#128 [Feature] 투두, 기록 기능 제거
  app/src/main/java/com/coldblue/haru_mandalart/HMApplication.kt
  app/src/main/java/com/coldblue/haru_mandalart/MainActivity.kt
  core/data/src/main/java/com/coldblue/data/alarm/BootCompletedReceiver.kt
  core/data/src/main/java/com/coldblue/data/sync/worker/SyncReadWorker.kt
  core/data/src/main/java/com/coldblue/data/sync/worker/SyncWriteWorker.kt
Labels: Feature

#129 [Feature] Splash 개선
  app/src/main/java/com/coldblue/haru_mandalart/MainActivity.kt
  app/src/main/res/values/themes.xml
  feature/login/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: Feature

#133 [Feature] Manda - Update Note ViewModel, Repo 추가
  app/src/main/java/com/coldblue/haru_mandalart/MainActivity.kt
  app/src/main/java/com/coldblue/haru_mandalart/util/SettingHelperImpl.kt
  core/data/src/main/java/com/coldblue/data/di/RepositoryModule.kt
  core/data/src/main/java/com/coldblue/data/repository/manda/MandaKeyRepository.kt
  core/data/src/main/java/com/coldblue/data/repository/manda/MandaKeyRepositoryImpl.kt
  core/data/src/main/java/com/coldblue/data/repository/manda/UpdateNoteRepository.kt
  core/data/src/main/java/com/coldblue/data/repository/manda/UpdateNoteRepositoryImpl.kt
  core/domain/src/main/java/com/coldblue/domain/manda/GetUpdateNoteUseCase.kt
  core/network/src/main/java/com/coldblue/network/datasource/UpdateNoteDataSource.kt
  core/network/src/main/java/com/coldblue/network/datasourceImpl/UpdateNoteNoteDataSourceImpl.kt
  feature/login/src/main/res/values/strings.xml
  feature/manda/src/main/java/com/coldblue/mandalart/MandaViewModel.kt
  feature/manda/src/main/java/com/coldblue/mandalart/UpdateNoteViewModel.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/MandaScreen.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/UpdateDialog.kt
  feature/manda/src/main/java/com/coldblue/mandalart/state/MandaUpdateDialogState.kt
Labels: Feature

#134 [Feature] Manda - Update Note, Explain Page
  core/data/src/main/java/com/coldblue/data/repository/user/UserRepository.kt
  core/data/src/main/java/com/coldblue/data/repository/user/UserRepositoryImpl.kt
  core/datastore/src/main/java/com/coldblue/datastore/UserDataSource.kt
  core/datastore/src/main/java/com/coldblue/datastore/UserDataSourceImpl.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMText.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMTextDialog.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/theme/Color.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/theme/Type.kt
  core/domain/src/main/java/com/coldblue/domain/user/GetExplainStateUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/user/UpdateExplainStateUseCase.kt
  feature/history/src/main/java/com/coldblue/history/content/HistoryContent.kt
  feature/login/src/main/java/com/coldblue/login/LoginScreen.kt
  feature/manda/src/main/java/com/coldblue/mandalart/ExplainViewModel.kt
  feature/manda/src/main/java/com/coldblue/mandalart/UpdateNoteViewModel.kt
  feature/manda/src/main/java/com/coldblue/mandalart/model/MandaUI.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/MandaBottomSheet.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/MandaExplainPage.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/MandaScreen.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/UpdateDialog.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/content/InitializedMandaContent.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/content/UnInitializedMandaContent.kt
  feature/manda/src/main/java/com/coldblue/mandalart/state/MandaUpdateDialogState.kt
  feature/manda/src/main/res/drawable/explain_first_manda.png
  feature/manda/src/main/res/drawable/explain_second_manda.png
  feature/manda/src/main/res/drawable/explain_third_manda.png
  feature/manda/src/main/res/values/strings.xml
  feature/setting/src/main/java/com/coldblue/setting/content/SettingContent.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoBottomSheet.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoGroupBottomSheet.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoScreen.kt
  feature/todo/src/main/java/com/coldblue/todo/component/HMDatePicker.kt
  feature/todo/src/main/java/com/coldblue/todo/component/HMTimePicker.kt
  feature/todo/src/main/java/com/coldblue/todo/dialog/SimpleDialog.kt
Labels: Feature

#136 [Feature] Setting Screen
  app/src/main/java/com/coldblue/haru_mandalart/navigation/HMNavHost.kt
  app/src/main/java/com/coldblue/haru_mandalart/ui/HMApp.kt
  app/src/main/java/com/coldblue/haru_mandalart/ui/HMState.kt
  core/data/src/main/java/com/coldblue/data/util/LoginHelper.kt
  core/data/src/main/java/com/coldblue/data/util/LoginHelperImpl.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMTopBar.kt
  core/domain/src/main/java/com/coldblue/domain/auth/DeleteUserUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/auth/GetAuthStateUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/auth/GetComposeAuthUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/auth/LoginSucceededUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/auth/LoginWithOutAuthUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/auth/LogoutUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/network/GetNetworkStateUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/setting/GetVersionUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/setting/ShowContactUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/setting/ShowOssUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/setting/ShowPlayStoreUseCase.kt
  feature/login/src/main/java/com/coldblue/login/LoginScreen.kt
  feature/login/src/main/java/com/coldblue/login/LoginViewModel.kt
  feature/manda/src/main/java/com/coldblue/mandalart/MandaViewModel.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/MandaBottomSheet.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/MandaScreen.kt
  feature/setting/src/main/java/com/coldblue/setting/NoticeScreen.kt
  feature/setting/src/main/java/com/coldblue/setting/NoticeViewModel.kt
  feature/setting/src/main/java/com/coldblue/setting/SettingScreen.kt
  feature/setting/src/main/java/com/coldblue/setting/SettingViewModel.kt
  feature/setting/src/main/java/com/coldblue/setting/content/SettingContent.kt
  feature/setting/src/main/java/com/coldblue/setting/navigation/SettingNavigation.kt
Labels: Feature

#135 [Feature] String Resource, Explain Page, Mandalart Design
  app/src/main/java/com/coldblue/haru_mandalart/MainActivity.kt
  app/src/main/java/com/coldblue/haru_mandalart/util/SettingHelperImpl.kt
  app/src/main/res/values/strings.xml
  core/designsystem/src/main/java/com/coldblue/designsystem/theme/Color.kt
  core/designsystem/src/main/res/values/strings.xml
  feature/history/src/main/java/com/coldblue/history/HistoryScreen.kt
  feature/history/src/main/java/com/coldblue/history/content/HistoryContent.kt
  feature/history/src/main/res/values/strings.xml
  feature/login/src/main/java/com/coldblue/login/LoginScreen.kt
  feature/login/src/main/res/values/strings.xml
  feature/manda/src/main/java/com/coldblue/mandalart/screen/ExplainScreen.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/MandaBottomSheet.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/MandaScreen.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/UpdateDialog.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/content/InitializedMandaContent.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/content/UnInitializedMandaContent.kt
  feature/manda/src/main/java/com/coldblue/mandalart/util/MandaUtils.kt
  feature/manda/src/main/res/drawable/explain_first_manda.png
  feature/manda/src/main/res/drawable/explain_second_manda.png
  feature/manda/src/main/res/drawable/explain_third_manda.png
  feature/manda/src/main/res/values/strings.xml
  feature/setting/src/main/java/com/coldblue/setting/content/SettingContent.kt
  feature/setting/src/main/res/values/strings.xml
Labels: Feature

#138 [Feature] Explain Module, Mandalart Text Field
  app/build.gradle.kts
  app/src/main/java/com/coldblue/haru_mandalart/MainActivity.kt
  core/data/src/main/java/com/coldblue/data/util/LoginHelperImpl.kt
  core/data/src/main/java/com/coldblue/data/util/LoginState.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMTitleComponent.kt
  feature/explain/.gitignore
  feature/explain/build.gradle.kts
  feature/explain/consumer-rules.pro
  feature/explain/proguard-rules.pro
  feature/explain/src/androidTest/java/com/coldblue/explain/ExampleInstrumentedTest.kt
  feature/explain/src/main/AndroidManifest.xml
  feature/explain/src/main/java/com/coldblue/explain/ExplainScreen.kt
  feature/explain/src/main/java/com/coldblue/explain/ExplainViewModel.kt
  feature/explain/src/main/java/com/coldblue/explain/navigation/ExplainNavigation.kt
  feature/explain/src/main/res/drawable/explain_first_manda.png
  feature/explain/src/main/res/drawable/explain_second_manda.png
  feature/explain/src/main/res/drawable/explain_third_manda.png
  feature/explain/src/main/res/values/strings.xml
  feature/explain/src/test/java/com/coldblue/explain/ExampleUnitTest.kt
  feature/manda/src/main/java/com/coldblue/mandalart/MandaViewModel.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/MandaBottomSheet.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/MandaScreen.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/MandaTextField.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/content/InitializedMandaContent.kt
  feature/manda/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: Feature

#139 [Feature] 공지사항 & 기능제안
  app/build.gradle.kts
  app/src/main/java/com/coldblue/haru_mandalart/navigation/HMNavHost.kt
  app/src/main/java/com/coldblue/haru_mandalart/ui/HMState.kt
  core/data/src/main/java/com/coldblue/data/di/RepositoryModule.kt
  core/data/src/main/java/com/coldblue/data/mapper/NoticeMapper.kt
  core/data/src/main/java/com/coldblue/data/mapper/SurveyMapper.kt
  core/data/src/main/java/com/coldblue/data/repository/notice/NoticeRepository.kt
  core/data/src/main/java/com/coldblue/data/repository/notice/NoticeRepositoryImpl.kt
  core/data/src/main/java/com/coldblue/data/repository/survey/SurveyRepository.kt
  core/data/src/main/java/com/coldblue/data/repository/survey/SurveyRepositoryImpl.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/BottomSpacer.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/TopSpacer.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/theme/Color.kt
  core/domain/src/main/java/com/coldblue/domain/notice/GetNoticeListUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/notice/GetNoticeUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/survey/GetSurveyListUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/survey/GetSurveyUseCase.kt
  core/model/src/main/java/com/coldblue/model/Notice.kt
  core/model/src/main/java/com/coldblue/model/Survey.kt
  core/network/src/main/java/com/coldblue/network/datasource/NoticeDataSource.kt
  core/network/src/main/java/com/coldblue/network/datasource/SurveyDataSource.kt
  core/network/src/main/java/com/coldblue/network/datasourceImpl/NoticeDataSourceImpl.kt
  core/network/src/main/java/com/coldblue/network/datasourceImpl/SurveyDataSourceImpl.kt
  core/network/src/main/java/com/coldblue/network/di/SupabaseModule.kt
  core/network/src/main/java/com/coldblue/network/model/NetworkNotice.kt
  core/network/src/main/java/com/coldblue/network/model/NetworkSurvey.kt
  core/network/src/main/java/com/coldblue/network/model/NetworkSurveyLike.kt
  feature/notice/.gitignore
  feature/notice/build.gradle.kts
  feature/notice/src/androidTest/java/com/coldblue/notice/ExampleInstrumentedTest.kt
  feature/notice/src/main/AndroidManifest.xml
  feature/notice/src/main/java/com/coldblue/notice/NoticeScreen.kt
  feature/notice/src/main/java/com/coldblue/notice/NoticeUiState.kt
  feature/notice/src/main/java/com/coldblue/notice/NoticeViewModel.kt
  feature/notice/src/main/java/com/coldblue/notice/content/NoticeContent.kt
  feature/notice/src/main/java/com/coldblue/notice/navigation/NoticeNavigation.kt
  feature/notice/src/test/java/com/coldblue/notice/ExampleUnitTest.kt
  feature/setting/build.gradle.kts
  feature/setting/src/main/java/com/coldblue/setting/NoticeScreen.kt
  feature/setting/src/main/java/com/coldblue/setting/NoticeViewModel.kt
  feature/setting/src/main/java/com/coldblue/setting/SettingScreen.kt
  feature/setting/src/main/java/com/coldblue/setting/SettingViewModel.kt
  feature/setting/src/main/java/com/coldblue/setting/content/SettingContent.kt
  feature/setting/src/main/java/com/coldblue/setting/navigation/SettingNavigation.kt
  feature/survey/.gitignore
  feature/survey/build.gradle.kts
  feature/survey/src/androidTest/java/com/coldblue/survey/ExampleInstrumentedTest.kt
  feature/survey/src/main/AndroidManifest.xml
  feature/survey/src/main/java/com/coldblue/survey/SurveyDetailScreen.kt
  feature/survey/src/main/java/com/coldblue/survey/SurveyDetailViewModel.kt
  feature/survey/src/main/java/com/coldblue/survey/SurveyScreen.kt
  feature/survey/src/main/java/com/coldblue/survey/SurveyUiState.kt
  feature/survey/src/main/java/com/coldblue/survey/SurveyViewModel.kt
  feature/survey/src/main/java/com/coldblue/survey/content/SurveyDetailContent.kt
  feature/survey/src/main/java/com/coldblue/survey/content/SurveyListContent.kt
  feature/survey/src/main/java/com/coldblue/survey/navigation/SurveyNavigation.kt
  feature/survey/src/test/java/com/coldblue/survey/ExampleUnitTest.kt
  settings.gradle.kts
Labels: Feature

#140 [Feature] 기능제안
  app/src/main/java/com/coldblue/haru_mandalart/ui/HMState.kt
  core/data/src/main/java/com/coldblue/data/repository/survey/SurveyRepository.kt
  core/data/src/main/java/com/coldblue/data/repository/survey/SurveyRepositoryImpl.kt
  core/domain/src/main/java/com/coldblue/domain/auth/GetAuthStateUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/survey/UpdateSurveyUseCase.kt
  core/network/src/main/java/com/coldblue/network/datasource/SurveyDataSource.kt
  core/network/src/main/java/com/coldblue/network/datasourceImpl/SurveyDataSourceImpl.kt
  core/network/src/main/java/com/coldblue/network/model/NetworkSurveyLike.kt
  feature/notice/src/main/java/com/coldblue/notice/NoticeScreen.kt
  feature/notice/src/main/java/com/coldblue/notice/NoticeViewModel.kt
  feature/survey/src/main/java/com/coldblue/survey/SurveyDetailScreen.kt
  feature/survey/src/main/java/com/coldblue/survey/SurveyDetailViewModel.kt
  feature/survey/src/main/java/com/coldblue/survey/SurveyScreen.kt
  feature/survey/src/main/java/com/coldblue/survey/SurveyViewModel.kt
  feature/survey/src/main/java/com/coldblue/survey/content/SurveyDetailContent.kt
  feature/survey/src/main/java/com/coldblue/survey/content/SurveyListContent.kt
  feature/survey/src/main/java/com/coldblue/survey/navigation/SurveyNavigation.kt
Labels: Feature

#142 [Feature] Manda TextField, Update Dialog Logic
  app/src/main/java/com/coldblue/haru_mandalart/ui/HMApp.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMTopBar.kt
  feature/explain/build.gradle.kts
  feature/explain/consumer-rules.pro
  feature/explain/proguard-rules.pro
  feature/explain/src/main/java/com/coldblue/explain/ExplainScreen.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/MandaBottomSheet.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/MandaBox.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/MandaScreen.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/MandaTextField.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/content/InitializedMandaContent.kt
  feature/setting/build.gradle.kts
  settings.gradle.kts
Labels: Feature

#141 [Feature] Top Title Component, String Resource, Notice Expanded Animation
  app/src/main/java/com/coldblue/haru_mandalart/navigation/HMNavHost.kt
  app/src/main/java/com/coldblue/haru_mandalart/ui/HMApp.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/__IconPack.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMTopBar.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/iconpack/Mandalart.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/content/InitializedMandaContent.kt
  feature/notice/src/main/java/com/coldblue/notice/NoticeScreen.kt
  feature/notice/src/main/java/com/coldblue/notice/content/NoticeContent.kt
  feature/notice/src/main/java/com/coldblue/notice/navigation/NoticeNavigation.kt
  feature/setting/src/main/java/com/coldblue/setting/SettingScreen.kt
  feature/setting/src/main/java/com/coldblue/setting/content/SettingContent.kt
  feature/setting/src/main/java/com/coldblue/setting/navigation/SettingNavigation.kt
  feature/setting/src/main/res/values/strings.xml
  feature/survey/src/main/java/com/coldblue/survey/SurveyDetailScreen.kt
  feature/survey/src/main/java/com/coldblue/survey/SurveyScreen.kt
  feature/survey/src/main/java/com/coldblue/survey/content/SurveyListContent.kt
  feature/survey/src/main/java/com/coldblue/survey/navigation/SurveyNavigation.kt
Labels: Feature

#143 [Feature] 배포 전 피드백
  app/src/main/java/com/coldblue/haru_mandalart/util/SettingHelperImpl.kt
  core/datastore/src/main/java/com/coldblue/datastore/UserDataSourceImpl.kt
  feature/notice/src/main/java/com/coldblue/notice/NoticeScreen.kt
  feature/setting/src/main/java/com/coldblue/setting/content/SettingContent.kt
  feature/setting/src/main/java/com/coldblue/setting/state/DialogType.kt
  feature/setting/src/main/res/values/strings.xml
  feature/survey/src/main/java/com/coldblue/survey/SurveyScreen.kt
Labels: Test

#144 [Feature] 기능제안
  app/build.gradle.kts
  core/network/src/main/java/com/coldblue/network/datasourceImpl/NoticeDataSourceImpl.kt
  core/network/src/main/java/com/coldblue/network/datasourceImpl/SurveyDataSourceImpl.kt
  feature/notice/src/main/java/com/coldblue/notice/NoticeViewModel.kt
  feature/setting/src/main/java/com/coldblue/setting/content/SettingContent.kt
  feature/survey/src/main/java/com/coldblue/survey/SurveyDetailScreen.kt
Labels: Feature

#145 [Feature] change manda explain image
  app/build.gradle.kts
  feature/explain/src/main/java/com/coldblue/explain/ExplainScreen.kt
  feature/explain/src/main/res/drawable/explain_first_manda.png
  feature/explain/src/main/res/drawable/explain_manda_first.png
  feature/explain/src/main/res/drawable/explain_manda_second.png
  feature/explain/src/main/res/drawable/explain_manda_third.png
  feature/explain/src/main/res/drawable/explain_second_manda.png
  feature/explain/src/main/res/drawable/explain_third_manda.png
Labels: Feature

#146 [Feature] change manda explain image
  feature/explain/src/main/res/drawable/explain_manda_first.png
Labels: Feature
