Repository haru-mandal-art/haru-mandalart, pull requests merged in 2024-02, with the labels that each got.

#4 [Setting] 라이브러리 버전 최신화
  gradle/libs.versions.toml
Labels: Setting

#9 [Setting ]디자인 시스템
  app/src/main/java/com/coldblue/haru_mandalart/navigation/HMDestination.kt
  app/src/main/java/com/coldblue/haru_mandalart/navigation/HMNavHost.kt
  app/src/main/java/com/coldblue/haru_mandalart/navigation/TopLevelDestination.kt
  app/src/main/java/com/coldblue/haru_mandalart/ui/HMApp.kt
  app/src/main/java/com/coldblue/haru_mandalart/ui/HMState.kt
  core/data/src/main/java/com/coldblue/data/navi/Route.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/__IconPack.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMNavigationBarItem.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/iconpack/History.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/iconpack/Home.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/iconpack/Manda.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/theme/Color.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/theme/Theme.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/theme/Type.kt
  core/designsystem/src/main/res/font/orbit.ttf
  feature/history/src/main/java/com/coldblue/history/navigation/HistoryNavigation.kt
  feature/login/src/main/java/com/coldblue/login/navigation/LoginNavigation.kt
  feature/manda/src/main/java/com/coldblue/mandalart/navigation/MandaNavigation.kt
  feature/setting/src/main/java/com/coldblue/setting/navigation/SettingNavigation.kt
  feature/todo/src/main/java/com/coldblue/todo/navigation/TodoNavigation.kt
  feature/tutorial/src/main/java/com/coldblue/tutorial/navigation/TutorialNavigation.kt
Labels: Setting

#10 [Login] 로그인 로직 구현 완료
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/coldblue/haru_mandalart/MainActivity.kt
  app/src/main/java/com/coldblue/haru_mandalart/navigation/HMNavHost.kt
  app/src/main/java/com/coldblue/haru_mandalart/ui/HMApp.kt
  core/data/build.gradle.kts
  core/data/src/main/java/com/coldblue/data/repo/UserRepo.kt
  core/data/src/main/java/com/coldblue/data/repo/UserRepoImpl.kt
  core/data/src/main/java/com/coldblue/data/util/LoginHelper.kt
  core/data/src/main/java/com/coldblue/data/util/LoginHelperImpl.kt
  core/database/build.gradle.kts
  core/designsystem/src/main/java/com/coldblue/designsystem/component/LoginButton.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/theme/Theme.kt
  core/designsystem/src/main/res/drawable/pupple_icon.png
  core/designsystem/src/main/res/drawable/white_icon.png
  core/domain/build.gradle.kts
  core/domain/src/main/java/com/coldblue/domain/user/GetComposeAuthUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/user/UpdateUserTokenUseCase.kt
  core/network/build.gradle.kts
  core/network/src/main/java/com/coldblue/network/SupabaseDataSource.kt
  core/network/src/main/java/com/coldblue/network/SupabaseDataSourceImpl.kt
  core/network/src/main/java/com/coldblue/network/di/SupabaseModule.kt
  feature/login/build.gradle.kts
  feature/login/src/main/java/com/coldblue/login/LoginScreen.kt
  feature/login/src/main/java/com/coldblue/login/LoginViewModel.kt
  feature/login/src/main/java/com/coldblue/login/navigation/LoginNavigation.kt
Labels: Feature

#31 [Bug] Resolve Git Conflict
  core/data/src/main/java/com/coldblue/data/mapper/Mapper.kt
  core/database/src/main/java/com/coldblue/database/AppDataBase.kt
  core/database/src/main/java/com/coldblue/database/di/DaoModule.kt
Labels: Bug

#32 [Feature] TodoList, Group 기본 완성
  core/data/src/main/java/com/coldblue/data/di/RepoModule.kt
  core/data/src/main/java/com/coldblue/data/mapper/CurrentGroupMapper.kt
  core/data/src/main/java/com/coldblue/data/mapper/TodoMapper.kt
  core/data/src/main/java/com/coldblue/data/repo/CurrentGroupRepository.kt
  core/data/src/main/java/com/coldblue/data/repo/CurrentGroupRepositoryImpl.kt
  core/database/src/main/java/com/coldblue/database/dao/TodoDao.kt
  core/database/src/main/java/com/coldblue/database/entity/TodoEntity.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/__IconPack.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/TitleText.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/iconpack/Check.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/iconpack/Plus.kt
  core/domain/src/main/java/com/coldblue/domain/todogroup/GetCurrentGroupUseCase.kt
  core/model/src/main/java/com/coldblue/model/CurrentGroup.kt
  core/model/src/main/java/com/coldblue/model/Todo.kt
  core/model/src/main/java/com/coldblue/model/TodoGroup.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoScreen.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoUiState.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoViewModel.kt
Labels: Feature

#33 [Manda] Feaback, Final Goal Page, Manda Status
  core/data/src/main/java/com/coldblue/data/di/RepoModule.kt
  core/data/src/main/java/com/coldblue/data/mapper/Mapper.kt
  core/data/src/main/java/com/coldblue/data/repo/MandaDetailRepository.kt
  core/data/src/main/java/com/coldblue/data/repo/MandaDetailRepositoryImpl.kt
  core/data/src/main/java/com/coldblue/data/repo/MandaKeyRepository.kt
  core/data/src/main/java/com/coldblue/data/repo/MandaKeyRepositoryImpl.kt
  core/data/src/main/java/com/coldblue/data/repo/MandaRepo.kt
  core/data/src/main/java/com/coldblue/data/repo/MandaRepoImpl.kt
  core/data/src/main/java/com/coldblue/data/repo/UserRepository.kt
  core/data/src/main/java/com/coldblue/data/repo/UserRepositoryImpl.kt
  core/database/src/main/java/com/coldblue/database/di/DaoModule.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMButton.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMChip.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMEditText.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMTextField.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMTitleComponent.kt
  core/domain/src/main/java/com/coldblue/domain/manda/DeleteMandaDetailUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/manda/DeleteMandaKeyUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/manda/GetAllMandaUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/manda/GetDetailMandaUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/manda/GetKeyMandaUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/manda/InsertMandaDetailUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/manda/InsertMandaKeyUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/manda/UpdateMandaDetailUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/manda/UpdateMandaKeyUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/manda/UpsertMandaDetailUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/manda/UpsertMandaKeyUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/user/GetMandaInitStateUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/user/GetUserTokenUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/user/UpdateMandaInitStateUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/user/UpdateUserTokenUseCase.kt
  core/model/src/main/java/com/coldblue/model/MandaKey.kt
  core/model/src/main/java/com/coldblue/model/MandaTag.kt
  feature/manda/src/main/java/com/coldblue/mandalart/MandaScreen.kt
  feature/manda/src/main/java/com/coldblue/mandalart/MandaViewModel.kt
  feature/manda/src/main/java/com/coldblue/mandalart/state/MandaUIState.kt
  feature/manda/src/main/java/com/coldblue/mandalart/util/Utils.kt
  feature/manda/src/main/res/values/Array.xml
Labels: Feature

#34 [Feature] BottomSheet,Dialog 기본 완성
  core/model/src/main/java/com/coldblue/model/ToggleInfo.kt
  feature/todo/src/main/java/com/coldblue/todo/BottomSheetUiState.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoGroupBottomSheetWithState.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoScreen.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoUiState.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoViewModel.kt
Labels: Feature

#35 [Feature] Manda - Data Logic ,피드백 수정
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMButton.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMTextField.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMTitleComponent.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/TitleText.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/theme/Type.kt
  core/domain/src/main/java/com/coldblue/domain/manda/UpsertMandaDetailUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/manda/UpsertMandaKeyUseCase.kt
  core/model/src/main/java/com/coldblue/model/Manda.kt
  core/model/src/main/java/com/coldblue/model/MandaDetail.kt
  core/model/src/main/java/com/coldblue/model/MandaKey.kt
  feature/manda/src/main/java/com/coldblue/mandalart/MandaScreen.kt
  feature/manda/src/main/java/com/coldblue/mandalart/MandaViewModel.kt
  feature/manda/src/main/java/com/coldblue/mandalart/model/MandaUI.kt
  feature/manda/src/main/java/com/coldblue/mandalart/state/MandaUIState.kt
  feature/manda/src/main/java/com/coldblue/mandalart/util/Utils.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoScreen.kt
Labels: Feature

#36 [Bug] 병합 충돌 수정
  feature/manda/src/main/java/com/coldblue/mandalart/util/Utils.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoGroupBottomSheetWithState.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoScreen.kt
Labels: Bug

#37 [Feature] 그룹 bottomsheet, dialog 완성
  core/data/src/main/java/com/coldblue/data/mapper/CurrentGroupMapper.kt
  core/data/src/main/java/com/coldblue/data/mapper/TodoGroupMapper.kt
  core/data/src/main/java/com/coldblue/data/mapper/TodoMapper.kt
  core/data/src/main/java/com/coldblue/data/repo/CurrentGroupRepository.kt
  core/data/src/main/java/com/coldblue/data/repo/CurrentGroupRepositoryImpl.kt
  core/database/src/main/java/com/coldblue/database/dao/CurrentGroupDao.kt
  core/domain/src/main/java/com/coldblue/domain/todogroup/DeleteCurrentGroupUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/todogroup/GetCurrentGroupUseCase.kt
  core/domain/src/main/java/com/coldblue/domain/todogroup/GetGroupWithCurrentUseCase.kt
  core/model/src/main/java/com/coldblue/model/CurrentGroup.kt
  core/model/src/main/java/com/coldblue/model/GroupWithCurrent.kt
  core/model/src/main/java/com/coldblue/model/Todo.kt
  core/model/src/main/java/com/coldblue/model/TodoGroup.kt
  core/model/src/main/java/com/coldblue/model/ToggleInfo.kt
  feature/todo/src/main/java/com/coldblue/todo/BottomSheetUiState.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoBottomSheet.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoGroupBottomSheet.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoScreen.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoUiState.kt
  feature/todo/src/main/java/com/coldblue/todo/TodoViewModel.kt
Labels: Feature

#38 [Feature] Manda - UI, Logic
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMMainButton.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMMandaCompleteButton.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMMandaEmptyButton.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMMandaFillButton.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMMandaOutlineButton.kt
  core/designsystem/src/main/java/com/coldblue/designsystem/component/HMTextField.kt
  core/model/src/main/java/com/coldblue/model/MandaCombine.kt
  feature/manda/src/main/java/com/coldblue/mandalart/MandaScreen.kt
  feature/manda/src/main/java/com/coldblue/mandalart/MandaViewModel.kt
  feature/manda/src/main/java/com/coldblue/mandalart/model/MandaUI.kt
  feature/manda/src/main/java/com/coldblue/mandalart/navigation/MandaNavigation.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/MandaScreen.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/content/InitializedMandaContent.kt
  feature/manda/src/main/java/com/coldblue/mandalart/screen/content/UnInitializedMandaContent.kt
  feature/manda/src/main/java/com/coldblue/mandalart/state/MandaUIState.kt
  feature/manda/src/main/java/com/coldblue/mandalart/util/MandaUtils.kt
  feature/manda/src/main/java/com/coldblue/mandalart/util/Utils.kt
Labels: Feature
